# Copyright (c) 2022-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

name: Publish CloudZero CostFormation
description: Publish a new version of CloudZero CostFormation definition to the CloudZero platform.
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  file:
    description: The file containing the definitions
    required: true
  api-key:
    description: Your organizations API Key for accessing CloudZero APIs (this should be stored as a secret)
    required: true
  validate-only:
    description: If set to 'true', it will only validate the definitions. If set to 'false', then it will publish them
    required: false
    default: 'false'
  host:
    description: The host address of the CloudZero platform
    required: false
    default: api.cloudzero.com
runs:
  using: "composite"
  steps:
    - id: execute-curl
      run: |
        curl --fail-with-body --request POST --url https://${{ inputs.host }}/v2/costformation/definition/versions?validate_only=${{ inputs.validate-only }} -F data=@${{ inputs.file }} --header 'Content-Type: multipart/form-data' --header 'Authorization: ${{ inputs.api-key }}'
      shell: bash
