name: Pipeline

on:
  push:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - run: action-validator -v action.yaml